[twipi]
# ssh srv.us -R 1:/var/run/twipi.sock
listen_addr = "unix:///run/user/1000/twipi.sock"

[twipi.secrets]
account_sid = "${TWILIO_ACCOUNT_SID}"
auth_token = "${TWILIO_AUTH_TOKEN}"

[twipi.webhook.message]
enable = true
incoming_endpoint = "/webhooks/messages/incoming"
delivery_endpoint = "/webhooks/messages/delivery"

[discord]
database = "sqlite:///tmp/twidiscord.db"

[[discord.accounts]]
token = "${DISCORD_TOKEN}"
user_number = "${DISCORD_PHONE_NUMBER}"
twilio_number = "${TWILIO_PHONE_NUMBER}"
