[twid]
enable = true

[twid.http]
# ssh srv.us -R 1:/var/run/twipi.sock
listen_addr = "unix:///run/user/1000/twipi.sock"

[twipi]
enable = true

[twipi.message]
enable = true

[twipi.message.webhook]
incoming_endpoint = "/webhooks/messages/incoming"
delivery_endpoint = "/webhooks/messages/delivery"

[[twipi.accounts]]
base_url = "${TWILIO_BASE_URL}"
override = true
phone_number = "${TWILIO_PHONE_NUMBER}"
account_sid = "${TWILIO_ACCOUNT_SID}"
auth_token = "${TWILIO_AUTH_TOKEN}"
